let express=require("express")
const { adduser, login, islogin, isadmin } = require("../controllers/usercon")
const { resetpwd, sendotp } = require("../controllers/resetpwdcont")
const { add, getall, upload, getr, getbyid, addcomm, search, getrt, delprod, upd, updimg } = require("../controllers/prodcont")
const { addcart, incqty, decqty, delcart, getcart } = require("../controllers/cartcont")

let rt=new express.Router()
rt.post("/reg",adduser)
rt.post("/login",login)
rt.post("/resetpwd",resetpwd)
rt.get("/sendotp/:uid",sendotp)

rt.post("/addprod",upload.single("pimg"),islogin,isadmin,add)
rt.get("/get",getall)
rt.get("/retail/:rid",getr)
rt.post("/addcart",addcart)
rt.get("/inc/:cid",incqty)
rt.get("/dec/:cid",decqty)
rt.delete("/del/:cid",delcart)
rt.get("/getcart/:uid",getcart)
rt.get("/getbyid/:pid",getbyid)
rt.put("/addcomm",addcomm)
rt.post("/search",search)
rt.get("/getrt/:rid",getrt)
rt.delete("/delprod/:pid",delprod)
rt.put("/upd",upd)
rt.post("/updimg",upload.single("pimg"),updimg)
module.exports=rt